version: '3.8'

services:
  rails:
    build: ./rails
    volumes:
      - ./rails/backend:/rails:delegated
    ports:
      - "3000:3000"
    command: bash -lc "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  vue1:
    build: ./vue
    volumes:
      - ./vue/frontend:/vue:delegated
    ports:
      - "8080:8080"
  vue2:
    build: ./vue
    volumes:
      - ./vue/frontend:/vue:delegated
    ports:
      - "8081:8080"
